theme: jekyll-theme-slate
title: Paddle-SG
description: You can't buy happiness, but you can go kayaking <br/> <h6><font color="white">Site will be down for maintenance from 23 to 27 January 2018</font></h6>
show_downloads: false
google_analytics: UA-104918500-1
