theme: jekyll-theme-slate
title: Paddle-SG
description: You can't buy happiness, but you can go kayaking <br/> <h6 style="color: #FFFFFF"> Site will be down for maintenance from 8 to 11 December </h6>
show_downloads: false
google_analytics: UA-104918500-1
